### ISSUE TITLE
angular breakes url

### ISSUE THREAD

**Issue by fridmaster** [CanopyTax/single-spa-angular1#34]
Hi! Added this package to application which use webpack and I already use there packages for Angula2 and React, faced with issue that if I change url in the browser to angular app - it brakes url. Looks like it tried to be a parent app. Maybe Can I change something in config?
example I use link like this : http://localhost:9090/#/app3 -> http://localhost:9090/#!#%2Fapp3

**Comment by TheMcMurder** [comment]
Hey @fridmaster I'm going to need a bit more information to help.

Keep in mind that Single-spa-angular1 is just a small helper library for working with single-spa.

You mentioned that your application already has Angular2 and React, are you trying to use AngularJS, Angular2/4/5, and React all together?

Do you have Angular2/4/5 and react working together already? How is your project being built are you building it all with a single webpack config like we are here: https://github.com/joeldenning/simple-single-spa-webpack-example, or are you doing something different?

It looks like a config issue to me, but I don't know for sure because I can't see your config.

**Comment by joeldenning** [comment]
@fridmaster I think I reproduced your problem and found a solution. For hash routing, you should add the following line to your code:

```js
  $locationProvider.hashPrefix('');
```

Apparently this is a recent change in angular@1.6.7, this wasn't necessary in 1.6.1. See https://docs.angularjs.org/guide/$location for more documentation on it.

Let me know if that does/doesn't work!

**Comment by fridmaster** [comment]
@joeldenning Thank you so much! it is working now!!
